### ISSUE TITLE
Error when enabling newsroom_connector_newsletter module

### ISSUE THREAD

**Issue by StefanieVermandele** [LOBsTerr/newsroom_connector#5] opened 2022-12-29 12:54 UTC
I enabled the newsroom_connector_newsletter module with drush and it threw this warning and error:

`[warning] The configuration name "language.content_settings.taxonomy_term.newsroom_newsletter." does not match the ID "taxonomy_term.newsroom_newsletter" ConfigInstaller.php:394`
`In EntityStorageBase.php line 553:`
`  'language_content_settings' entity with ID 'taxonomy_term.newsroom_newsletter' already exists.`

Enabling the submodule through the UI caused a fatal error:

`Drupal\Core\Entity\EntityStorageException: 'language_content_settings' entity with ID 'taxonomy_term.newsroom_newsletter' already exists. in Drupal\Core\Entity\EntityStorageBase->doPreSave() (line 553 of core/lib/Drupal/Core/Entity/EntityStorageBase.php).`

**Comment by LOBsTerr** [comment] 2023-01-03 10:44
Hm, I tried to reproduce on the current instance, everything is ok. Then reinstall a completely fresh instance and sill ok. 
Can't reproduce it

**Comment by LOBsTerr** [comment] 2023-05-22 16:54
Close it, since there is no additional info. Fill free to open

**Closed by LOBsTerr** 2023-05-22 16:54 UTC
